export const candidatesData = [
    {
      id: 1,
      name: 'John Doe',
      assignmentLink: 'https://example.com/assignment1',
      assignmentHour: '2',
      image:'https://cdn.pixabay.com/photo/2023/10/25/04/25/ai-generated-8339489_1280.png',
      endHour: '5',
      about:"Lorem ipsum dolor sit amet, consectetur adipiscing elit",
      score:'78%',
      behavioralScore: 8,
      communicationScore: 9,
      situationHandlingScore: 7,
      experience: '3 years of experience in software development',
      hobbies: 'Playing guitar, hiking',
      introduction: 'Hello, I am John Doe...',
    },
    {
      id: 2,
      name: 'Jane Smith',
      about:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquam massa magna, vel condimentum tortor tempor sit amet. Nulla quis condimentum turpis. Fusce vestibulum ultricies velit, eu fermentum ex tincidunt eget. Nam eget feugiat turpis, vel lobortis nulla. Integer ac dui sit amet felis hendrerit vestibulum. Cras ac erat vel ligula luctus aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut varius tincidunt libero, non consequat erat lobortis sit amet. Vivamus lacinia varius sapien non tempus. Aenean vel metus vestibulum, dignissim est ac, varius eros. Vestibulum vulputate nulla ac lectus dignissim, eu tempus elit aliquet",
      score:'78%',
      assignmentLink: 'https://example.com/assignment2',
      assignmentHour: '3',
      endHour: '6',
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzB2DWWEwCQ_PaD2hX8lksny3EIU3CF-AnCkYibjJBXw&s",
      behavioralScore: 9,
      communicationScore: 8,
      situationHandlingScore: 9,
      experience: '5 years of experience in project management',
      hobbies: 'Reading, cooking',
      introduction: 'Hi there, I am Jane Smith...',
    },
    {
      id: 3,
      name: 'Emily Johnson',
      assignmentLink: 'https://example.com/assignment3',
      assignmentHour: '4',
      about:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquam massa magna, vel condimentum tortor tempor sit amet. Nulla quis condimentum turpis. Fusce vestibulum ultricies velit, eu fermentum ex tincidunt eget. Nam eget feugiat turpis, vel lobortis nulla. Integer ac dui sit amet felis hendrerit vestibulum. Cras ac erat vel ligula luctus aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut varius tincidunt libero, non consequat erat lobortis sit amet. Vivamus lacinia varius sapien non tempus. Aenean vel metus vestibulum, dignissim est ac, varius eros. Vestibulum vulputate nulla ac lectus dignissim, eu tempus elit aliquet",
      endHour: '7',
      image:'https://img.freepik.com/premium-photo/smiling-beautiful-woman-standing-her-against-white-background-created-with-generative-ai_762026-47573.jpg',
      behavioralScore: 7,
      communicationScore: 9,
      score:'78%',
      situationHandlingScore: 8,
      experience: '2 years of experience in marketing',
      hobbies: 'Painting, traveling',
      introduction: 'Nice to meet you, I am Emily Johnson...',
    },
    {
      id: 4,
      name: 'Michael Brown',
      assignmentLink: 'https://example.com/assignment4',
      assignmentHour: '5',
      endHour: '8',
      about:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquam massa magna, vel condimentum tortor tempor sit amet. Nulla quis condimentum turpis. Fusce vestibulum ultricies velit, eu fermentum ex tincidunt eget. Nam eget feugiat turpis, vel lobortis nulla. Integer ac dui sit amet felis hendrerit vestibulum. Cras ac erat vel ligula luctus aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut varius tincidunt libero, non consequat erat lobortis sit amet. Vivamus lacinia varius sapien non tempus. Aenean vel metus vestibulum, dignissim est ac, varius eros. Vestibulum vulputate nulla ac lectus dignissim, eu tempus elit aliquet",
      score:'78%',
      behavioralScore: 9,
      communicationScore: 7,
      situationHandlingScore: 8,
      experience: '4 years of experience in sales',
      hobbies: 'Playing football, watching movies',
      introduction: 'Hello everyone, I am Michael Brown...',
    },
    {
      id: 5,
      name: 'Olivia Garcia',
      assignmentLink: 'https://example.com/assignment5',
      assignmentHour: '6',
      about:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquam massa magna, vel condimentum tortor tempor sit amet. Nulla quis condimentum turpis. Fusce vestibulum ultricies velit, eu fermentum ex tincidunt eget. Nam eget feugiat turpis, vel lobortis nulla. Integer ac dui sit amet felis hendrerit vestibulum. Cras ac erat vel ligula luctus aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut varius tincidunt libero, non consequat erat lobortis sit amet. Vivamus lacinia varius sapien non tempus. Aenean vel metus vestibulum, dignissim est ac, varius eros. Vestibulum vulputate nulla ac lectus dignissim, eu tempus elit aliquet",
      endHour: '9',
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiFo5APmmLc34sU1mbeRxOcUJuZOjwYyZyNgePEz0lyfceU_kDm63Y5eWBlY_yqjMqSJ4&usqp=CAU",
      behavioralScore: 8,
      communicationScore: 5,
      score:'78%',
      situationHandlingScore: 9,
      experience: '3 years of experience in customer service',
      hobbies: 'Photography, cooking',
      introduction: 'Greetings! I am Olivia Garcia...',
    },
    {
      id: 6,
      name: 'Ethan Martinez',
      assignmentLink: 'https://example.com/assignment6',
      assignmentHour: '7',
      endHour: '10',
      about:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquam massa magna, vel condimentum tortor tempor sit amet. Nulla quis condimentum turpis. Fusce vestibulum ultricies velit, eu fermentum ex tincidunt eget. Nam eget feugiat turpis, vel lobortis nulla. Integer ac dui sit amet felis hendrerit vestibulum. Cras ac erat vel ligula luctus aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut varius tincidunt libero, non consequat erat lobortis sit amet. Vivamus lacinia varius sapien non tempus. Aenean vel metus vestibulum, dignissim est ac, varius eros. Vestibulum vulputate nulla ac lectus dignissim, eu tempus elit aliquet",
      score:'78%',
      image:"https://i2-prod.dailystar.co.uk/incoming/article30004223.ece/ALTERNATES/s1200b/0_Screenshot-2023-05-17-at-142751.jpg",
      behavioralScore: 9,
      communicationScore: 9,
      situationHandlingScore: 9,
      experience: '6 years of experience in software engineering',
      hobbies: 'Playing basketball, hiking',
      introduction: 'Hey there, I am Ethan Martinez...',
    },
    {
      id: 7,
      name: 'Sophia Taylor',
      assignmentLink: 'https://example.com/assignment7',
      assignmentHour: '8',
      endHour: '11',
      about:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris aliquam massa magna, vel condimentum tortor tempor sit amet. Nulla quis condimentum turpis. Fusce vestibulum ultricies velit, eu fermentum ex tincidunt eget. Nam eget feugiat turpis, vel lobortis nulla. Integer ac dui sit amet felis hendrerit vestibulum. Cras ac erat vel ligula luctus aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut varius tincidunt libero, non consequat erat lobortis sit amet. Vivamus lacinia varius sapien non tempus. Aenean vel metus vestibulum, dignissim est ac, varius eros. Vestibulum vulputate nulla ac lectus dignissim, eu tempus elit aliquet",
      behavioralScore: 7,
      communicationScore: 8,
      situationHandlingScore: 7,
      experience: '2 years of experience in graphic design',
      hobbies: 'Reading novels, painting',
      introduction: 'Pleased to meet you, I am Sophia Taylor...',
    },
    {
      id: 8,
      name: 'William Hernandez',
      assignmentLink: 'https://example.com/assignment8',
      assignmentHour: '9',
      endHour: '12',
      behavioralScore: 8,
      communicationScore: 9,
      situationHandlingScore: 8,
      experience: '4 years of experience in finance',
      hobbies: 'Playing piano, gardening',
      introduction: 'Hello, I am William Hernandez...',
    },
    {
      id: 9,
      name: 'Ava Thomas',
      assignmentLink: 'https://example.com/assignment9',
      assignmentHour: '10',
      endHour: '13',
      behavioralScore: 9,
      communicationScore: 9,
      situationHandlingScore: 9,
      experience: '5 years of experience in human resources',
      hobbies: 'Yoga, traveling',
      introduction: 'Nice to meet you all, I am Ava Thomas...',
    },
    {
      id: 10,
      name: 'James Wilson',
      assignmentLink: 'https://example.com/assignment10',
      assignmentHour: '11',
      endHour: '14',
      behavioralScore: 8,
      communicationScore: 7,
      situationHandlingScore: 8,
      experience: '3 years of experience in education',
      hobbies: 'Playing guitar, hiking',
      introduction: 'Greetings, I am James Wilson...',
    },
  ];
  